import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ConnectWallet from "./components/ConnectWallet"
import { AImodel } from './components/AImodel'
import { Notifications } from './components/Notifications'
import NotificationsPopover from './components/NotificationsPopover'
import AccountPopover from './components/AccountPopover'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      <ConnectWallet/>
      <AImodel/>
      <Notifications/>
      <NotificationsPopover/>
      <AccountPopover/>



      </main>
    </>
  )
}
